a=set()
a.add(1)
a.add(2)
a.add(3)
a.add(4)
print("conjubto a",a)
b=set()
b.add(1)
b.add(2)
b.add(3)
b.add(4)
b.add(5)
b.add(6)
c=set()
c.add(1)
c.add(2)
c.add(3)
c.add(4)
c.add(5)
c.add(6)
print("conjunto b",c)
c.discard(5)
print(b)
d=a.copy
print.a=copy
c.clear()
print("conjunto c",c)
c=b.copy()
print(c)
print(c.isdisjoint(b))
e=set()
e.add(3)
e.add(4)
print(c.issubset(a))
print(c.issubset(b))
print(c.issubset(c))
print(c.issubset(d))
print(c.issuperset(a))
f=c.union(b)
print("conjunto f",f)
a.update(b)
print("conjunto f",a)
print(a.difference(b))
a.difference_update(b)
print("conjunto a",a)
c.intersection(d)
print(c.intersection_update(d))
print("conjunt a",a)
print("conjunt b",b)
print("conjunt c",c)
print("conjunt d",d)
print("conjunt e",e)
print("conjunt f",f)
print(c.symmetric_difference(d))






    